### ISSUE TITLE
Pre-check wether image exists before container uses it  

### ISSUE THREAD

**Issue by luwensu** [autotest/autotest-docker#533]
Like what https://github.com/autotest/autotest-docker/pull/532 says 

What i see is all kill\* sub-case lack of an image check before
the container.execute(), thus the case would fail once the default image doesn't exist.

Using default_image_exist_check() in DockerImage
instance to check whether default image exists before run it.

**Comment by cevich** [comment]
Oh great, I'm glad you figured it out!  This was on my (long) list of things to look into.  The only (minor) complication here is, 'docker pull' can now block if the image is being downloaded in the background (due to some other request).  This could lead to timeouts, but this is not a problem which couldn't be noticed otherwise, so it's no big deal.  I think your #532 solution is good and in the right direction, let's use that to fix this issue.  Thanks!

**Comment by cevich** [comment]
Closing this as we've added functionality via a pre-test to pull down and/or build test images
